### ISSUE TITLE
PathCreator namespace still not found within project assembly

### ISSUE THREAD

**Issue by douthwja01** [douthwja01/CSI-cobotics#21]
The Bezier tools still aren't able to find the path creator package. This is without the packages moving or changes to the code so i suspect its something else?

**Comment by Gaudeval** [comment]
Is there more information on the issue? Where is the package reference failing? What is referenced and by whom?

**Comment by douthwja01** [comment]
If you create the bezier path planner and drop it in the scene, the error produced simply says than none of the scripts can find their assemblies?

**Comment by Gaudeval** [comment]
It seems the Bezier Path Planner prefab is missing some of the required components. I will see update it.
